### ISSUE TITLE
'bash Flakify_predict.sh' error

### ISSUE THREAD

**Issue by Marvinmw** [uOttawa-Nanda-Lab/Flakify#1]
Start time of the experiment 1644578339.3052166
Traceback (most recent call last):
  File "Flakify_predictor.py", line 341, in <module>
    for train_index, test_index in skf.split(input_data, target_data):
  File "sklearn/model_selection/_split.py", line 747, in split
    y = check_array(y, ensure_2d=False, dtype=None)
  File "/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

**Comment by sakinafatima** [comment]
hello, 
This issue has been fixed. It was due to Microsoft Excel which has added blank spaces in the dataset while saving the file. Please clone the recent changes. Thanks and let us know if you need any other information.
